import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Docs",
  description:
    "Get started with the VantaPM CLI, package installation flow, configuration format, and publishing basics.",
  alternates: {
    canonical: "/docs",
  },
};

export default function DocsPage() {
  return (
    <div className="space-y-8">
      <section>
        <h1 className="font-[family-name:var(--font-syne)] text-3xl font-bold">Docs</h1>
        <p className="mt-2 text-[var(--color-text-secondary)]">
          Minimal v1 documentation for installing and using the Vanta CLI.
        </p>
      </section>

      <section className="card-surface p-6">
        <h2 className="font-[family-name:var(--font-syne)] text-2xl font-semibold">Getting Started</h2>
        <div className="mt-4 space-y-3 font-[family-name:var(--font-mono)] text-sm">
          <div className="rounded-md border border-[var(--color-border)] bg-[var(--color-bg)] px-3 py-2">
            npm install -g @vanta/cli
          </div>
          <div className="rounded-md border border-[var(--color-border)] bg-[var(--color-bg)] px-3 py-2">
            vanta init
          </div>
          <div className="rounded-md border border-[var(--color-border)] bg-[var(--color-bg)] px-3 py-2">
            vanta install &lt;package&gt;
          </div>
        </div>
      </section>

      <section className="card-surface p-6">
        <h2 className="font-[family-name:var(--font-syne)] text-2xl font-semibold">packman.toml format</h2>
        <p className="mt-2 text-sm text-[var(--color-text-secondary)]">
          Project configuration file generated by <span className="font-[family-name:var(--font-mono)]">vanta init</span>.
        </p>
        <pre className="mt-4 overflow-auto rounded-md border border-[var(--color-border)] bg-[var(--color-bg)] p-4 font-[family-name:var(--font-mono)] text-xs text-[var(--color-text-secondary)]">
{`[project]
name = "my-firmware"
chip = "esp32-s3"
framework = "espidf"

[dependencies]
arduinojson = "^7.0.0"
radiolib = "^6.5.0"

[build]
optimization = "size"
warnings_as_errors = false`}
        </pre>
        <ul className="mt-4 space-y-2 text-sm text-[var(--color-text-secondary)]">
          <li><span className="font-[family-name:var(--font-mono)] text-[var(--color-text-primary)]">project.name</span> — your firmware/app name</li>
          <li><span className="font-[family-name:var(--font-mono)] text-[var(--color-text-primary)]">project.chip</span> — target MCU (for compatibility checks)</li>
          <li><span className="font-[family-name:var(--font-mono)] text-[var(--color-text-primary)]">project.framework</span> — Arduino / ESP-IDF / etc.</li>
          <li><span className="font-[family-name:var(--font-mono)] text-[var(--color-text-primary)]">dependencies</span> — package names and semver ranges</li>
          <li><span className="font-[family-name:var(--font-mono)] text-[var(--color-text-primary)]">build.*</span> — build-level options used by the CLI/build tools</li>
        </ul>
      </section>

      <section className="card-surface p-6">
        <h2 className="font-[family-name:var(--font-syne)] text-2xl font-semibold">CLI reference</h2>
        <div className="mt-4 space-y-3 text-sm text-[var(--color-text-secondary)]">
          {[
            ["vanta init", "Create packman.toml for a new project."],
            ["vanta search mqtt", "Search registry packages by keyword."],
            ["vanta install arduinojson", "Install and lock a package."],
            ["vanta add radiolib", "Add dependency entry without install."],
            ["vanta list", "List installed packages from lockfile."],
            ["vanta update", "Update packages within semver constraints."],
            ["vanta publish", "Publish your library metadata to the registry."],
          ].map(([cmd, desc]) => (
            <div key={cmd} className="rounded-md border border-[var(--color-border)] bg-[var(--color-bg)] p-3">
              <p className="font-[family-name:var(--font-mono)] text-[var(--color-text-primary)]">{cmd}</p>
              <p className="mt-1 text-xs">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="card-surface p-6">
        <h2 className="font-[family-name:var(--font-syne)] text-2xl font-semibold">Quality scores</h2>
        <p className="mt-2 text-sm text-[var(--color-text-secondary)]">
          Vanta quality score is 0–100, computed from five categories (each worth 20 points):
        </p>
        <ul className="mt-3 space-y-2 text-sm text-[var(--color-text-secondary)]">
          <li><span className="text-[var(--color-text-primary)]">Maintenance (0–20)</span> — recency of commits and activity</li>
          <li><span className="text-[var(--color-text-primary)]">CI/Tests (0–20)</span> — CI setup and presence of tests</li>
          <li><span className="text-[var(--color-text-primary)]">Documentation (0–20)</span> — README quality and examples</li>
          <li><span className="text-[var(--color-text-primary)]">Popularity (0–20)</span> — stars and ecosystem traction</li>
          <li><span className="text-[var(--color-text-primary)]">Compatibility (0–20)</span> — platform/framework coverage</li>
        </ul>
      </section>

      <section className="card-surface p-6">
        <h2 className="font-[family-name:var(--font-syne)] text-2xl font-semibold">Publishing a package</h2>
        <ol className="mt-3 list-decimal space-y-2 pl-5 text-sm text-[var(--color-text-secondary)]">
          <li>Ensure your repo has a clear README and license.</li>
          <li>Add manifest metadata (`library.properties` or `idf_component.yml`) with version info.</li>
          <li>Run <span className="font-[family-name:var(--font-mono)] text-[var(--color-text-primary)]">vanta publish</span> and provide repository URL.</li>
          <li>Registry crawler validates metadata, computes quality, and indexes your package.</li>
          <li>Your package appears in search and platform-filtered listings after indexing.</li>
        </ol>
      </section>
    </div>
  );
}
